"""
Markdown report renderer for SimpleReconDorking.

Converts the list of per-run result dicts (produced by Engine.run()) into a
human-readable Markdown document suitable for delivering to clients, pasting
into GitHub issues/PRs, or viewing in any Markdown renderer.

Pure function - no I/O, no global state.
"""
from __future__ import annotations

from datetime import datetime


# ── Section builders ──────────────────────────────────────────────────────────

def _esc(s: str) -> str:
    """Escape pipe characters inside table cells."""
    return str(s).replace('|', '\\|')


def _header(seed: str, dorks: list, sources: dict, urls: set) -> str:
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    engine_list = ', '.join(f'`{s}`' for s in sorted(sources)) if sources else '-'
    return (
        f'# Dorking Report - {seed}\n\n'
        f'**Date:** {ts}  \n'
        f'**Dorks run:** {len(dorks)}  \n'
        f'**Engines:** {engine_list}  \n'
        f'**URLs discovered:** {len(urls)}'
    )


def _summary_table(urls: set, extra_filtered: set) -> str:
    rows = [
        ('URLs discovered', len(urls)),
        ('Filtered-out URLs', len(extra_filtered)),
    ]

    lines = ['## Summary', '', '| Metric | Value |', '|--------|-------|']
    for label, value in rows:
        lines.append(f'| {label} | {value} |')
    return '\n'.join(lines)


def _all_urls_section(urls: set) -> str:
    if not urls:
        return ''
    lines = ['## All URLs', '', '```']
    lines.extend(sorted(urls))
    lines.append('```')
    return '\n'.join(lines)


def _extras_section(extras: dict) -> str:
    filtered = sorted(extras.get('urls_filtered', set()))
    if not filtered:
        return ''
    lines = [
        '## Extras', '',
        '### Filtered-out URLs (excluded by an active --filter-*)', '',
        '```',
    ]
    lines += filtered[:50]
    if len(filtered) > 50:
        lines.append(f'… and {len(filtered) - 50} more')
    lines.append('```')
    return '\n'.join(lines)


def _sources_section(sources: dict) -> str:
    if not sources:
        return ''
    lines = [
        '## Engine Contributions', '',
        '| Engine | URLs |',
        '|--------|------|',
    ]
    for src, count in sorted(sources.items(), key=lambda x: -x[1]):
        lines.append(f'| `{src}` | {count} |')
    return '\n'.join(lines)


def _dorks_section(dorks: list, url_dorks: dict) -> str:
    """Per-dork breakdown: how many URLs each query actually returned."""
    if not dorks:
        return ''
    per_dork: dict[str, int] = {d: 0 for d in dorks}
    for dork in url_dorks.values():
        per_dork[dork] = per_dork.get(dork, 0) + 1
    lines = [
        '## Dorks Run', '',
        '| Dork | URLs |',
        '|------|------|',
    ]
    for dork in dorks:
        lines.append(f'| `{_esc(dork)}` | {per_dork.get(dork, 0)} |')
    return '\n'.join(lines)


# ── Public API ────────────────────────────────────────────────────────────────

def render_markdown(results: list[dict]) -> str:
    """
    Render a Markdown dorking report from a list of Engine result dicts.

    Returns the full report as a single string.
    """
    sections: list[str] = []

    for result in results:
        seed           = result.get('seed', '')
        dorks          = result.get('dorks', []) or []
        urls           = result.get('urls', set()) or set()
        sources        = result.get('sources', {}) or {}
        url_dorks      = result.get('url_dorks', {}) or {}
        extras         = result.get('extras', {}) or {}
        extra_filtered = extras.get('urls_filtered', set()) or set()

        sections.append(_header(seed, dorks, sources, urls))
        sections.append(_summary_table(urls, extra_filtered))

        sections.append(_all_urls_section(urls))

        extras_sec = _extras_section(extras)
        if extras_sec:
            sections.append(extras_sec)

        src_sec = _sources_section(sources)
        if src_sec:
            sections.append(src_sec)

        dorks_sec = _dorks_section(dorks, url_dorks)
        if dorks_sec:
            sections.append(dorks_sec)

        sections.append('---\n\n*Generated by [SimpleReconDorking v1](https://github.com/osintbrazuca/SimpleReconDorking)*')

    return '\n\n---\n\n'.join(sections)
